# Claim of persistent storage for the postgres-upgrade project
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-upgrade
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  volumeName: postgres-upgrade
  resources:
    requests:
      storage: 4.5G