# StatefulSet for the postgres-upgrade project
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres-upgrade
spec:
  replicas: 1
  serviceName: postgres-upgrade
  template:
    spec:
      initContainers:
      - name: pg-checksums
        image: tianon/postgres-upgrade:17-to-18
        command: ["/bin/sh", "-c"]
        args:
        - "/usr/lib/postgresql/17/bin/pg_checksums --pgdata /var/lib/postgresql/data/17/ --enable --progress"
        #- "/usr/lib/postgresql/17/bin/pg_checksums --disable --pgdata /var/lib/postgresql/data/17/"
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
      containers:
      - name: pg-upgrade
        image: tianon/postgres-upgrade:17-to-18
        ports:
        - name: pg-upgrade
          containerPort: 50432
        env:
        - name: PGDATAOLD
          valueFrom:
            configMapKeyRef:
              name: postgres-upgrade-config
              key: postgresql-db-data-old-path
        - name: PGDATANEW
          valueFrom:
            configMapKeyRef:
              name: postgres-upgrade-config
              key: postgresql-db-data-new-path
        resources:
          requests:
            cpu: "0.75"
            memory: 256Mi
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
        - name: postgresql-config
          readOnly: true
          subPath: postgresql.conf
          mountPath: /etc/postgresql/postgresql.conf
      volumes:
      - name: postgresql-config
        configMap:
          name: postgres-upgrade-config
          defaultMode: 444
          items:
          - key: postgresql.conf
            path: postgresql.conf
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: postgres-upgrade
