# Setup for the postgres-upgrade project
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-upgrade

labels:
- pairs:
    app: postgres-upgrade
  includeSelectors: true
  includeTemplates: true

resources:
- resources/postgres-upgrade.namespace.yaml
- resources/postgres-upgrade.persistentvolumeclaim.yaml
- resources/postgres-upgrade.persistentvolume.yaml
- resources/postgres-upgrade.statefulset.yaml

replicas:
- name: postgres-upgrade
  count: 1

images:
- name: tianon/postgres-upgrade
  newTag: 17-to-18

configMapGenerator:
- name: postgres-upgrade-config
  envs:
  - configs/dbdatapaths.properties
  files:
  - configs/postgresql.conf
