# Persistent storage volume for the Forgejo server users' Git repositories and LFS contents
apiVersion: v1
kind: PersistentVolume

metadata:
  name: forgejo-hdd-git
spec:
  capacity:
    storage: 19G
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/forgejo-hdd/git/k3smnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3sagent01