# Ghost MariaDB headless service
apiVersion: v1
kind: Service

metadata:
  name: db-mariadb
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3306
    targetPort: server
    protocol: TCP
    name: server
  - port: 9104
    targetPort: metrics
    protocol: TCP
    name: metrics