# Traefik IngressRoute for Headlamp
apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: headlamp
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`10.7.0.2`) || Host(`headlamp.homelab.cloud`) || Host(`hdl.homelab.cloud`)
    kind: Rule
    services:
    - name: headlamp
      kind: Service
      port: 80
  tls:
    secretName: headlamp.homelab.cloud-tls