apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: db-postgresql
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  volumeName: db-gitea
  resources:
    requests:
      storage: 3.5G
