apiVersion: v1
kind: Service

metadata:
  name: cache-redis
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
spec:
  type: ClusterIP
  clusterIP: 10.43.100.1
  ports:
  - port: 6379
    protocol: TCP
    name: server
  - port: 9121
    protocol: TCP
    name: metrics
