apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: db-mariadb
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  volumeName: db-nextcloud
  resources:
    requests:
      storage: 3.5G
