# Headlamp setup
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- resources/headlamp-admin.serviceaccount.yaml
- resources/cluster-admin-users.clusterrolebinding.yaml
- resources/headlamp.homelab.cloud-tls.certificate.cert-manager.yaml
- resources/headlamp.ingressroute.traefik.yaml
- https://raw.githubusercontent.com/kubernetes-sigs/headlamp/main/kubernetes-headlamp.yaml