# Forgejo server setup
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app: server-forgejo
  includeSelectors: true
  includeTemplates: true

resources:
- resources/server-forgejo-data.persistentvolumeclaim.yaml
- resources/server-forgejo-git.persistentvolumeclaim.yaml
- resources/server-forgejo.service.yaml
- resources/server-forgejo.statefulset.yaml

replicas:
- name: server-forgejo
  count: 1

images:
- name: docker.io/busybox
  newTag: stable-musl
- name: codeberg.org/forgejo/forgejo
  newTag: 14.0-rootless

configMapGenerator:
- name: server-forgejo-env-vars
  envs:
  - configs/env.properties

secretGenerator:
- name: server-forgejo-valkey-user
  envs:
  - secrets/valkey_user_env.properties
