# Prometheus Node Exporter headless service
apiVersion: v1
kind: Service

metadata:
  name: agent-prometheus-node-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9100'
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    protocol: TCP
    port: 9100
    targetPort: metrics
